// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  Altro: 'Other',
  'Elezioni maggio 2021': 'Elections May 2021',
  Programmi: 'Programs',
  Risultati: 'Results',
  'COORDINA I CORSI DI STUDIO E FORNISCE UN INDIRIZZO GENERALE ALLA SCUOLA.': 'COORDINATES THE COURSES OF STUDY AND PROVIDES A GENERAL ADDRESS TO THE SCHOOL.',
  'Contatti 💬': 'Contacts 💬',
  'Elezioni rappresentanti degli studenti': 'Election of student representatives',
  Scrivici: 'Write to us',
  Scuole: 'Schools' // school // schoolhouse
}
