// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  Altro: 'Other', // other // another // more // else // different // further // each other // second
  'Elezioni maggio 2021': 'Elections May 2021',
  Programmi: 'Programs', // program // plan // schedule // syllabus // timetable // programme
  Risultati: 'Results' // aftermath
}
